on:
    workflow_run:
      workflows: [Checkup]
      types:
        - completed
name: ðŸš€ Deploy website on push
jobs:
    web-deploy: 
        name: ðŸŽ‰ DÃ©ployement Site
        runs-on: ubuntu-latest
        steps:
        - name: ðŸšš Copy du code
          uses: actions/checkout@v4
        - name: ðŸ“‚ Syncronisation fichiers
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5
          with:
            server: ${{ secrets.ftp_server }}
            username: ${{ secrets.ftp_user }}
            password: ${{ secrets.ftp_password }}
            port: 21
            exclude: |
              **/.git*/**
              **/node_modules/**
              **/build/
              .README.MD
              .gitignore
              .htaccess